"""retry models creation

Revision ID: 686801013014
Revises: a22a5c0054c6
Create Date: 2024-09-14 13:21:57.613926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686801013014'
down_revision = 'a22a5c0054c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
